title: dtc innovation
tag_text: dtc innovation
description: Designing Technology for the Commons.
baseurl: ""
url: https://dtc-innovation.org
permalink: /writings/:year/:title

source_lang: en

collections_dir: collections
collections:
  projects_en:
    output: true
    permalink: /en/projects/:title
  projects_fr:
    output: true
    permalink: /projects/:title
  decisions:
    output: true
    permalink: /decisions/:year-:month-:day.html
  customers:
    output: false


company:
  siren: '823553557'
  siret: '82355355700013'
  vat: 'FR67823553557'
  formation: '75331173933'
  rna: 'W332020707'
  ape: '6201Z'
  since: 2016-09-16

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "writing"
      lang: "fr"
  - scope:
      path: ""
      type: "projects_fr"
    values:
      layout: "project"
      lang: "fr"
  - scope:
      path: ""
      type: "projects_en"
    values:
      layout: "project"
      lang: "en"
  - scope:
      path: ""
      type: "decisions"
    values:
      layout: "page"
      lang: "fr"
  - scope:
      path: ""
    values:
      lang: "fr"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-i18n_tags
