title: dtc innovation
tag_text: dtc innovation
description: >
  We design, prototype and engineer innovation for the web and for the commons.
baseurl: ""

font-awesome-include: false

collections:
  projects:
    resources:
      github: GitHub Project
      website: Website

# Build settings
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
